version: '3.4'

services:
  core.device:
    image: core.device
    build:
      context: .
      dockerfile: src/Core.Device/Dockerfile
    depends_on:
      - dynamodb
      - rabbit
  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - "8000:8000"
    environment:
      AWS_ACCESS_KEY_ID: root
      AWS_SECRET_ACCESS_KEY: secret
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"